apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: multitier
  labels:
    app.kubernetes.io/part-of: multitier-demo
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  DB_POOL_MAX: "10"
  PORT: "3000"
