apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: multitier
  labels:
    app.kubernetes.io/part-of: multitier-demo
type: Opaque
data:
  DB_PASSWORD: 
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 
  POSTGRES_DB:
