apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: multitier
  labels:
    app: postgres
    app.kubernetes.io/part-of: multitier-demo
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
