apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: multitier
  labels:
    app: postgres
    app.kubernetes.io/part-of: multitier-demo
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
