apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage-class
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer